#!/usr/bin/php
<?php
echo PHP_EOL;

require('hook-lib.php');



if (SUGGEST_COMMIT_MSG !== false) {

    //## Obtain the current branch name
    $branchName = getCurrentBranchName();
    $omsg       = file_get_contents($argv[1]);

    $msg = SUGGEST_COMMIT_MSG;
    $msg = str_replace('%b', $branchName, $msg);
    $msg = str_replace('%o', $omsg, $msg);

    file_put_contents($argv[1], $msg);

    echo 'Suggesting a commit message template.';
    echo PHP_EOL;
    exit(0);
}

exit(0);